# Generated by Django 5.1.4 on 2024-12-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10000)),
                ('image', models.URLField()),
                ('description', models.CharField(max_length=10000)),
                ('readers', models.CharField(max_length=100)),
            ],
        ),
    ]
