# Generated by Django 5.1.4 on 2024-12-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientmodel',
            name='calories',
            field=models.IntegerField(blank=True, null=True, verbose_name='укажите калорийность по желанию'),
        ),
        migrations.AddField(
            model_name='ingredientmodel',
            name='is_optional',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='ingredientmodel',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='укажите калорийность по желанию'),
        ),
        migrations.CreateModel(
            name='CollectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('recipes', models.ManyToManyField(to='recipes.recipemodel')),
            ],
        ),
    ]
